# Generated by Django 2.2.7 on 2020-02-05 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trendy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_1', models.CharField(max_length=255)),
                ('tag_2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurhash', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('delivery_price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=300)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('online', models.BooleanField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Coordinate')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Trendy')),
            ],
        ),
    ]
