# Generated by Django 2.2.7 on 2020-02-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_example'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Restaurants',
        ),
    ]
