# Generated by Django 2.2.7 on 2020-02-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200208_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='blurhash',
            field=models.CharField(max_length=300),
        ),
    ]
